# Generated by Django 5.1.3 on 2025-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="icon.svg", null=True, upload_to=""
            ),
        ),
    ]
